name: bump version reusable workflow

on:
  workflow_call:
    secrets:
        token:
          required: true

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      id: tag_version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true

    - id: step1
      run: echo "${{ steps.tag_version.outputs.new_tag}}"
    outputs: 
      output1: ${{ steps.step1.outputs.new_tag }}
      

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      OUTPUT1: ${{needs.build.outputs.output1}}
    steps:
      - name: print version number
        run: echo "${{ steps.build.outputs.new_tag }} $OUTPUT1"
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          tag: "$OUTPUT1"
          artifacts: "release.tar.gz,foo/*.txt"
